config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
  	resources :answers, only: [:create, :edit, :update, :destroy] do
  	  resources :votes, only: [:create, :update, :destroy]
  	end
    resources :votes, only: [:create, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :tags, :only => [:index]
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :votes, dependent: :destroy
  acts_as_taggable

  def vote_question_counts
    vote_plus = Vote.where(question_id: self.id, answer_id: nil, is_plus: true).count
    vote_minus = Vote.where(question_id: self.id, answer_id: nil, is_plus: false).count
    vote_count = vote_plus + (-1)*vote_minus
    if vote_count.blank?
      vote_count = 0
    end
    return vote_count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_question_tags_to_gon, only: [:edit]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = params[:tag].present? ? Question.tagged_with(params[:tag]) :Question.all
    @questions = @questions.includes(:tags)
    @questions_total = Question.count
    @tags = ActsAsTaggableOn::Tag.most_used(20)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = @question.answers.build
    @answers = @question.answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: '質問が投稿されました' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: '質問内容が更新されました' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: '質問が削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :tag_list)
    end

    def set_question_tags_to_gon
      gon.question_tags = @question.tag_list
    end

    def correct_user
      @question = Question.find(params[:id])
      unless @question.user_id == current_user.id
        redirect_to questions_path, alert: "他人の投稿は変更・削除出来ません"
      end
    end
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h4><%= @question.errors.count %>件のエラーがあります。以下を確認してください。</h4>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-7">
      <div class="row new_question_title_box">
        <div class="col-sm-2"><%= f.label :タイトル %></div>
        <div class="col-sm-10 pull-right"><%= f.text_field :title, class: "form-control" %></div>
      </div>
      <div class="row new_question_box">
        <%= f.text_area :content, class: "form-control", rows: 10 %>
      </div>
      <div class="row new_tag_box">
        <div class="admin-questions">
          <%= f.label :tag_list, "タグ(カンマ区切り)"%>
        <ul id="question-tags">     
        </ul>
      </div>
    </div>
    <div class="row new_question_submit_button">
      <%= f.submit "質問を投稿する", class: "btn submit" %>
    </div>
</div>
<% end %>

app/views/questions/_popular_questions.html.erb
<div class="row">
  <% @questions.order(favorite_count: :desc).each do |question| %>
    <div class="row question_row">
      <div class="col-sm-3">
        <div class="row vote_answer_count_area">
          <div class="col-sm-4">
            <div class="row text-center"><%= question.vote_question_counts %></div>
            <div class="row text-center">票</div>
          </div>
          <div class="col-sm-4">
            <div class="row text-center"><%= question.answers.count %></div>
            <div class="row text-center">回答</div>
          </div>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="row"><h4><%= link_to question.title, question_path(question) %></h4></div>
        <div class="tags">
          <div class="row"><%= render partial: 'tags', locals: { tags: question.tags} %></div>
        </div>
        <div class="row text-right"><%= question.created_at.strftime('%Y年%m月%d日 %H時%M分') %>&nbsp;&nbsp;<%= link_to question.user.name, question.user %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/_recent_questions.html.erb
<div class="row">
  <% @questions.order(created_at: :desc).each do |question| %>
    <div class="row question_row">
      <div class="col-sm-3">
        <div class="row vote_answer_count_area">
          <div class="col-sm-4">
            <div class="row text-center"><%= question.vote_question_counts %></div>
            <div class="row text-center">票</div>
          </div>
          <div class="col-sm-4">
            <div class="row text-center"><%= question.answers.count %></div>
            <div class="row text-center">回答</div>
          </div>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="row"><h4><%= link_to question.title, question_path(question) %></h4></div>
        <div class="tags">
          <div class="row"><%= render partial: 'tags', locals: { tags: question.tags} %></div>
        </div>
        <div class="row text-right"><%= question.created_at.strftime('%Y年%m月%d日 %H時%M分') %>&nbsp;&nbsp;<%= link_to question.user.name, question.user %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/_star.html.erb
<% if current_user.favorite?(question) %>
  <%= link_to question_favorite_path(question, question.favorites.find_by(user_id: current_user.id)), method: :delete do %>
    <div class="row star"><i class="fa fa-star fa-2x yellow"></i></div>
  <% end %>
  <div class="row fav_count text-center"><%= question.favorite_count %></div>
<% else %>
  <%= link_to question_favorites_path(question), method: :post do %>
    <div class="row star"><i class="fa fa-star fa-2x gray"></i></div>
  <% end %>
  <div class="row fav_count text-center"><%= question.favorite_count %></div>
<% end %>

app/views/questions/_tags.html.erb
<% tags.each do |tag|%>
  <div class="tag">
    <%= link_to "#{tag.name}", questions_path(tag: tag.name) %>
  </div>
<% end %>

app/views/questions/_vote.html.erb
<div class="vote">

  <% if current_user.vote_plus_question?(question) %>
    <%= fa_icon 'caret-up 4x', style: "color:#F69C55" %>
    <%= current_user.vote_question_counts(question) %>
    <%= link_to question_vote_path(question, question.votes.find_by(user_id: current_user.id, question_id: question.id, answer_id: nil)), method: :delete do %>
      <%= fa_icon 'caret-down 4x', style: "color:#818185" %>
    <% end %>
  <% elsif current_user.vote_minus_question?(question) %>
    <%= link_to question_vote_path(question, question.votes.find_by(user_id: current_user.id, question_id: question.id, answer_id: nil)), method: :delete do %>
      <%= fa_icon 'caret-up 4x', style: "color:#818185" %>
    <% end %>
    <%= current_user.vote_question_counts(question) %>
    <%= fa_icon 'caret-down 4x', style: "color:#F69C55" %>
  <% else %>
    <%= link_to question_votes_path(question, vote_result: true), method: :post do %>
      <%= fa_icon 'caret-up 4x', style: "color:#818185" %>
    <% end %>
    <%= current_user.vote_question_counts(question) %>
    <%= link_to question_votes_path(question, vote_result: false), method: :post do %>
      <%= fa_icon 'caret-down 4x', style: "color:#818185" %>
    <% end %>
  <% end %>
</div>

<!-- #818185  #F69C55 -->

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row question_index">
  <div class="col-sm-8">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>

    <div class="row">
      <h4 class="pull-left">すべての質問</h4>
      <ul class="nav nav-tabs">
        <li class="pull-right toggle_tabs"><a href="#tab2" data-toggle="tab">人気</a></li>
        <li class="active pull-right toggle_tabs"><a href="#tab1" data-toggle="tab">新着</a></li>
      </ul>
    </div>
    
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="tab1">
        <div class="row">
          <%= render partial: 'recent_questions', locals: { questions: @questions} %>
        </div>
      </div>
      <div class="tab-pane fade" id="tab2">
        <div class="row">
          <%= render partial: 'popular_questions', locals: { questions: @questions} %>
        </div>
      </div>
    </div>    
  </div>

  <div class="col-sm-4 question_index_sidebar">
    <div>
    <p>サイト統計情報</p>
      <h4><%= @questions_total %> 質問</h4>
    </div></br>
    <p>最新のタグ</p>
    <% @tags.each do |t| %>
      <div class="tag_box">
        <div class="tag"><%= link_to "#{t.name}", questions_path(tag: t.name) %></div> × <%= t.taggings_count %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>



<div class="row question_title">
  <h3><%= @question.title %></h3>
</div>

<div class="row">
  <div class="col-sm-9">
      <div class="row question">
      <div class="col-sm-1 question_buttons">
        <%= render partial: 'star', locals: { question: @question } %>
        <%= render partial: 'vote', locals: { question: @question } %>
      </div>
      <div class="col-sm-11 question_box">
        <div class="question_content"><%= simple_format(@question.content) %></div>
        <div class="question_tag"><%= render partial: 'tags', locals: { tags: @question.tags} %></div>
        <div class="question_btn_and_submitter">
          <div>
            <% if @question.user_id == current_user.id %>
              <%= link_to "質問内容を変更", edit_question_path(@question) %>
              <%= link_to "質問を削除", question_path(@question), method: :delete, data: { confirm: '本当に削除しても良いですか?' } %>
            <% end %>
          </div>
          <div class="pull-right"><%= @question.user.name %></div>
        </div>
      </div>
      </div>

      <div class="row answer_number"><%= @answers.count %>件の回答</div>
      <%= render partial: 'answers/index', locals: { answers: @answers, question: @question } %>

      <div class="row answer_title">回答</div>
      <%= render partial: 'answers/form', locals: { answer: @answer, question: @question } %>
  </div>

  <div class="col-sm-3">
    <p>投稿日時 <%= @question.created_at.strftime('%Y年%m月%d日 %H時%M分') %></p>
  </div>
</div>