config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
  	resources :answers, only: [:create, :edit, :update, :destroy] do
  	  resources :votes, only: [:create, :update, :destroy]
  	end
    resources :votes, only: [:create, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :tags, :only => [:index]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :content, presence: true
  
  belongs_to :user
  belongs_to :question
  has_many :votes, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def create
  	@answer = current_user.answers.build(answer_params)
    @question = @answer.question

    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_path(@question), notice: '回答を投稿しました。' }
      else
        format.html { redirect_to question_path(@question), notice: '回答を投稿できませんでした。回答内容を入力してください。'}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_path(@answer.question), notice: '回答内容が更新されました。' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { redirect_to edit_question_answer_path(@answer.question, @answer), notice: '回答を変更できませんでした。空欄で投稿は出来ません。' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@answer.destroy

    respond_to do |format|
      format.html { redirect_to question_path(@answer.question), notice: '回答が削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:question_id, :content)
    end

     def set_answer
      @answer = Answer.find(params[:id])
    end

    def correct_user 
      @answer = Answer.find(params[:id])
      unless @answer.user_id == current_user.id
        redirect_to question_path(@answer.question), alert: "他人の回答は変更・削除出来ません" 
      end
    end
end

app/views/answers/_form.html.erb
<%= form_for([question, answer]) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :question_id %>
  <div class="field">
    <%= f.text_area :content, class: "form-control", rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit "回答を投稿", class: "btn submit" %>
  </div>
<% end %>

app/views/answers/_index.html.erb
<% answers.each do |answer| %>
 <div class="row answer">
  <% unless answer.id.nil? %>
    <div class="col-sm-1 question_buttons">
    <%= render partial: 'answers/vote', locals: { question: answer.question, answer: answer } %>
 	</div>
 	<div class="col-sm-11 answer_box">
      <p><%= simple_format(answer.content) %></p>
      <% if current_user.id == answer.user.id %>
        <%= link_to 'この回答を改善する', edit_question_answer_path(question, answer) %>
        <%= link_to 'この回答を削除する', question_answer_path(question, answer), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
      <% end %>
      <div class="pull-right"><%= answer.user.name %></div>
    </div>
  <% end %>
</div>
<% end %>

app/views/answers/_vote.html.erb
<div class="vote">

  <% if current_user.vote_plus_answer?(question, answer) %>
    <%= fa_icon 'caret-up 4x', style: "color:#F69C55" %>
    <%= current_user.vote_answer_counts(question, answer) %>
    <%= link_to question_answer_vote_path(question, answer, question.votes.find_by(user_id: current_user.id, question_id: question.id, answer_id: answer.id)), method: :delete do %>
      <%= fa_icon 'caret-down 4x', style: "color:#818185" %>
    <% end %>
  <% elsif current_user.vote_minus_answer?(question, answer) %>
    <%= link_to question_answer_vote_path(question, answer, question.votes.find_by(user_id: current_user.id, question_id: question.id, answer_id: answer.id)), method: :delete do %>
      <%= fa_icon 'caret-up 4x', style: "color:#818185" %>
    <% end %>
    <%= current_user.vote_answer_counts(question, answer) %>
    <%= fa_icon 'caret-down 4x', style: "color:#F69C55" %>
  <% else %>
    <%= link_to question_answer_votes_path(question, answer, vote_result: true), method: :post do %>
      <%= fa_icon 'caret-up 4x', style: "color:#818185" %>
    <% end %>
    <%= current_user.vote_answer_counts(question, answer) %>
    <%= link_to question_answer_votes_path(question, answer, vote_result: false), method: :post do %>
      <%= fa_icon 'caret-down 4x', style: "color:#818185" %>
    <% end %>
  <% end %>

</div>

<!-- #818185  #F69C55 -->

app/views/answers/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <h4>回答を編集</h4>
</div>
<div class="row">
  <div class="col-sm-7">
    <%= form_for(@answer, url: question_answer_path) do |f| %>
      <div class="row new_question_box">
        <%= f.text_area :content, class: "form-control", rows: 10 %>
      </div>
      <div class="row new_question_submit_button">
        <%= f.submit '編集内容を保存', class: 'btn submit' %>
      </div>
    <% end %>
  </div>
</div>