config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
  	resources :answers, only: [:create, :edit, :update, :destroy] do
  	  resources :votes, only: [:create, :update, :destroy]
  	end
    resources :votes, only: [:create, :update, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :tags, :only => [:index]
end

app/views/layouts/_header.html.erb
<div class="row header">
  <div class="col-sm-3 pull-left">
    <%= image_tag 'stackoverflow.png', class: "hlogo" %>
  </div>

  <div class="col-sm-4 pull-right">
    <div class="btn-group">
    	<div class="form-inline">
          <%= link_to "質問", root_path, class: 'btn btn-default'%>
          <%= link_to "タグ", tags_path, class: 'btn btn-default'%>
          <%= link_to "ユーザー", users_path, class: 'btn btn-default'%>
          <%= link_to "質問する", new_question_path, class: 'btn btn-default'%>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>stack overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= include_gon %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "stack overflow", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, edit_user_registration_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

<div class="container">
  <%= render 'layouts/header' %>
  <%= yield %>
</div>

</body>
</html>